#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pycurl
Version  : 7.21.5
Release  : 16
URL      : http://pycurl.sourceforge.net/download/pycurl-7.21.5.tar.gz
Source0  : http://pycurl.sourceforge.net/download/pycurl-7.21.5.tar.gz
Summary  : PycURL -- cURL library module for Python
Group    : Development/Tools
License  : HPND LGPL-2.1
Requires: pycurl-python
Requires: pycurl-doc
BuildRequires : curl
BuildRequires : curl-dev
BuildRequires : openssl-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(libidn)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : zlib-dev

%description
PycURL: Python interface to libcurl
====================================
.. image:: https://api.travis-ci.org/pycurl/pycurl.png
:target: https://travis-ci.org/pycurl/pycurl

%package doc
Summary: doc components for the pycurl package.
Group: Documentation

%description doc
doc components for the pycurl package.


%package python
Summary: python components for the pycurl package.
Group: Default

%description python
python components for the pycurl package.


%prep
%setup -q -n pycurl-7.21.5

%build
python2 setup.py build -b py2 --with-ssl
python3 setup.py build -b py3 --with-ssl

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/pycurl/*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
